-- DATABASE testing

-- DROP SCHEMA ntch;

CREATE SCHEMA ntch AUTHORIZATION postgres;


-- ntch.banner definition

-- Drop table

-- DROP TABLE banner;

CREATE TABLE banner (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	created_at timestamp NULL,
	description varchar(255) NULL,
	image varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT banner_pkey PRIMARY KEY (id)
);


-- ntch.services definition

-- Drop table

-- DROP TABLE services;

CREATE TABLE services (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	code varchar(255) NULL,
	created_at timestamp NULL,
	icon varchar(255) NULL,
	"name" varchar(255) NULL,
	tarif int4 NULL,
	CONSTRAINT services_pkey PRIMARY KEY (id)
);


-- ntch.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	created_at timestamp NULL,
	email varchar(255) NULL,
	fullname varchar(255) NULL,
	"password" varchar(255) NULL,
	profile_pic varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- ntch.transaction_history definition

-- Drop table

-- DROP TABLE transaction_history;

CREATE TABLE transaction_history (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	transaction_type varchar(255) NOT NULL,
	user_id int4 NULL,
	created_at timestamp NULL,
	invoice_number varchar(255) NOT NULL,
	total_amount numeric(19, 2) NOT NULL,
	service_id int4 NULL,
	CONSTRAINT transaction_history_pkey PRIMARY KEY (id),
	CONSTRAINT fkjtip09wgc63pvuf3ydsy9p0ew FOREIGN KEY (service_id) REFERENCES services(id),
	CONSTRAINT fkpx4e8nnqbfyueh6nwqflbk9ro FOREIGN KEY (user_id) REFERENCES users(id)
);


-- ntch.user_balance definition

-- Drop table

-- DROP TABLE user_balance;

CREATE TABLE user_balance (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	balance numeric(19, 2) NOT NULL,
	user_id int4 NULL,
	CONSTRAINT user_balance_pkey PRIMARY KEY (id),
	CONSTRAINT fkdc2arkxowqwkfyhymlokgj7k0 FOREIGN KEY (user_id) REFERENCES users(id)
);


INSERT INTO banner
(created_at, description, image, "name")
VALUES(now(), 'Lerem Ipsum Dolor sit amet', 'https://nutech-integrasi.app/dummy.jpg', 'Banner 1');
INSERT INTO banner
(created_at, description, image, "name")
VALUES(now(), 'Lerem Ipsum Dolor sit amet', 'https://nutech-integrasi.app/dummy.jpg', 'Banner 2');
INSERT INTO banner
(created_at, description, image, "name")
VALUES(now(), 'Lerem Ipsum Dolor sit amet', 'https://nutech-integrasi.app/dummy.jpg', 'Banner 3');
INSERT INTO banner
(created_at, description, image, "name")
VALUES(now(), 'Lerem Ipsum Dolor sit amet', 'https://nutech-integrasi.app/dummy.jpg', 'Banner 4');
INSERT INTO banner
(created_at, description, image, "name")
VALUES(now(), 'Lerem Ipsum Dolor sit amet', 'https://nutech-integrasi.app/dummy.jpg', 'Banner 5');
INSERT INTO banner
(created_at, description, image, "name")
VALUES(now(), 'Lerem Ipsum Dolor sit amet', 'https://nutech-integrasi.app/dummy.jpg', 'Banner 6');


INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('PAJAK', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Pajak PBB', 40000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('PLN', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Listrik', 10000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('PDAM', now(), 'https://nutech-integrasi.app/dummy.jpg', 'PDAM Berlangganan', 40000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('PULSA', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Pulsa', 40000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('PGN', now(), 'https://nutech-integrasi.app/dummy.jpg', 'PGN Berlangganan', 50000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('MUSIK', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Musik Berlangganan', 50000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('TV', now(), 'https://nutech-integrasi.app/dummy.jpg', 'TV Berlangganan', 50000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('PAKET_DATA', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Paket data', 50000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('VOUCHER_GAME', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Voucher Game', 100000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('VOUCHER_MAKANAN', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Voucher Makanan', 100000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('QURBAN', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Qurban', 200000);
INSERT INTO services
(code, created_at, icon, "name", tarif)
VALUES('ZAKAT', now(), 'https://nutech-integrasi.app/dummy.jpg', 'Zakat', 300000);

